import type { Metadata } from 'next'
import { Inter, Prompt } from 'next/font/google'
import { getServerSession } from 'next-auth'

import './globals.css'
import './globalTemplate.css'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import NavBar from '@/components/basic/menu/NavBar'

const prompt = Prompt({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin', 'thai'],
})

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang='en'>
      <body className={prompt.className}>
        <NextAuthProvider session={session}>
          <NavBar />
          <div className='mt-[56px]'>{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
